// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: smarter.proto

package transfer

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Smarter service

func NewSmarterEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Smarter service

type SmarterService interface {
	Call(ctx context.Context, in *Req, opts ...client.CallOption) (*Res, error)
}

type smarterService struct {
	c    client.Client
	name string
}

func NewSmarterService(name string, c client.Client) SmarterService {
	return &smarterService{
		c:    c,
		name: name,
	}
}

func (c *smarterService) Call(ctx context.Context, in *Req, opts ...client.CallOption) (*Res, error) {
	req := c.c.NewRequest(c.name, "Smarter.Call", in)
	out := new(Res)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Smarter service

type SmarterHandler interface {
	Call(context.Context, *Req, *Res) error
}

func RegisterSmarterHandler(s server.Server, hdlr SmarterHandler, opts ...server.HandlerOption) error {
	type smarter interface {
		Call(ctx context.Context, in *Req, out *Res) error
	}
	type Smarter struct {
		smarter
	}
	h := &smarterHandler{hdlr}
	return s.Handle(s.NewHandler(&Smarter{h}, opts...))
}

type smarterHandler struct {
	SmarterHandler
}

func (h *smarterHandler) Call(ctx context.Context, in *Req, out *Res) error {
	return h.SmarterHandler.Call(ctx, in, out)
}
